name: Lint with flake8 and black
on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install flake8 black

    - name: Lint with flake8
      run: |
        flake8 src/ozone

    - name: Check style with black
      run: |
        black --check src
