name: Run linter check
on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install flake8 black mypy
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 src/

    - name: Check style with black
      run: |
        black --check src/

    - name: Lint with mypy
      run: |
        mypy --install-types --non-interactive --ignore-missing-imports src/
